[package]
name = "adrian-smb-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Fresh Rust SMB 3.1.1 server"

[dependencies]
adrian-smb-core = { path = "../adrian-smb-core" }
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
bytes.workspace = true
uuid.workspace = true
sha2.workspace = true
