[package]
name = "adrian-claims-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "AD FS claim rule language compatibility layer"

[dependencies]
adrian-policy-cel = { path = "../adrian-policy-cel" }
adrian-schema-traits = { path = "../adrian-schema-traits" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
